#include "logger.h"

int main()
{
  LOG_DEBUG("test %d", 1);
  y::lib::Logger::LogConfig(y::lib::Logger::LogLevel::INFO, 9128);
  LOG_DEBUG("test "
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddtest "
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddtest "
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddtest "
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddtest "
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddtest "
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddtest "
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddtest "
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddtest "
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddtest "
            "asdasdasdasdasdddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
            "ddddddddddddddddddddddddd%d",
            1);
}
